// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ52vGFfVzp9nJnpEakaM5GAuz05daU_w',
    appId: '1:279308869947:web:6a47b2bda7eb30ca61571e',
    messagingSenderId: '279308869947',
    projectId: 'crudtutorial-34449',
    authDomain: 'crudtutorial-34449.firebaseapp.com',
    storageBucket: 'crudtutorial-34449.firebasestorage.app',
    measurementId: 'G-88JG3BY004',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbS7Fu2w7YjefgDSGzv9fOb6fT87Vo014',
    appId: '1:279308869947:android:4d313cbcc6deb6ea61571e',
    messagingSenderId: '279308869947',
    projectId: 'crudtutorial-34449',
    storageBucket: 'crudtutorial-34449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXlfBuR0oFE4YwwAfg_L83nptFlGu0xZM',
    appId: '1:279308869947:ios:f0d4f351ff089f6461571e',
    messagingSenderId: '279308869947',
    projectId: 'crudtutorial-34449',
    storageBucket: 'crudtutorial-34449.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlfBuR0oFE4YwwAfg_L83nptFlGu0xZM',
    appId: '1:279308869947:ios:f0d4f351ff089f6461571e',
    messagingSenderId: '279308869947',
    projectId: 'crudtutorial-34449',
    storageBucket: 'crudtutorial-34449.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ52vGFfVzp9nJnpEakaM5GAuz05daU_w',
    appId: '1:279308869947:web:6512756a92ec831261571e',
    messagingSenderId: '279308869947',
    projectId: 'crudtutorial-34449',
    authDomain: 'crudtutorial-34449.firebaseapp.com',
    storageBucket: 'crudtutorial-34449.firebasestorage.app',
    measurementId: 'G-JL489EQWP0',
  );

}